name: bio
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anyio=4.6.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attrs=24.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - blinker=1.8.2
  - blosc=1.21.6
  - bokeh=3.5.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-blosc2=2.15.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - cairomm-1.16=1.16.2
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - epoxy=1.5.10
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - flask=3.0.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - glib-tools=2.82.1
  - gmp=6.3.0
  - graph-tool=2.77
  - graph-tool-base=2.77
  - graphite2=1.3.13
  - gtk3=3.24.43
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - hicolor-icon-theme=0.17
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.10.1
  - libcxx=19.1.1
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgirepository=1.82.0
  - libglib=2.82.1
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.44
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=19.1.0
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numexpr=2.10.0
  - openjpeg=2.5.2
  - openssl=3.3.2
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pycairo=1.27.0
  - pycparser=2.22
  - pygments=2.18.0
  - pygobject=3.50.0
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - pytables=3.10.1
  - python=3.12.6
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - scipy=1.14.1
  - send2trash=1.8.3
  - setuptools=75.1.0
  - sigcpp-3.0=3.6.0
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sparsehash=2.0.4
  - stack_data=0.6.2
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240906
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.4
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zlib-ng=2.2.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - adjusttext==1.2.0
      - airr==1.5.1
      - anndata==0.10.9
      - array-api-compat==1.8
      - biopython==1.84
      - changeo==1.3.0
      - distance==0.1.3
      - flask-login==0.6.3
      - h5py==3.12.1
      - igraph==0.11.6
      - joblib==1.4.2
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - llvmlite==0.43.0
      - mizani==0.9.3
      - natsort==8.4.0
      - networkx==3.3
      - numba==0.60.0
      - numpy==1.26.4
      - palettable==3.3.3
      - patsy==0.5.6
      - plotnine==0.12.4
      - polyleven==0.8
      - presto==0.7.2
      - pynndescent==0.5.13
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - sc-dandelion==0.3.8
      - scanpy==1.10.3
      - scikit-learn==1.5.2
      - seaborn==0.13.2
      - session-info==1.0.0
      - setuptools-scm==8.1.0
      - statsmodels==0.14.3
      - stdlib-list==0.10.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tqdm==4.66.5
      - umap-learn==0.5.6
      - xlrd==1.2.0
      - yamlordereddictloader==0.4.2