name: bio
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - scanpy
  - python-igraph
  - leidenalg
  - igblast
  - pip:
    - scanpy
    - sc-dandelion
    - flask
    - flask-wtf
    - bokeh
    - python-dotenv
      

